TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
# ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#=============================
# lkupRecord.h will be created from lkupRecord.dbd
DBDINC += lkupRecord

LIBRARY_IOC += lkup

# Add local files
lkup_SRCS += lkupRecord.cc

# lkup_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
# ADD RULES AFTER THIS LINE

